In [1]:
! pip3 install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 2.5 MB/s  0:00:02 eta 0:00:01m

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip


In [ ]:
import numpy as np

In [3]:
# Q1
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
# Q2
arr = np.zeros((3, 3))
arrr = np.ones((3,3))
print(arr)
print(arrr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Q3

arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
arr = np.arange(0, 20)
print(arr)
print(arr[1, 1:])
print(arr[::4, ::3 ])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed