In [1]:
import numpy as np


In [4]:
marks = np.array([35, 68, 42, 91, 27, 55])
print(np.where(marks>50, "pass" , "fail"))
# print(np.where(marks>50))

['fail' 'pass' 'fail' 'pass' 'fail' 'pass']


In [16]:
marks = np.array([92, 61, 45, 78, 33, 55])
condi = np.where(marks>=75, 'A', 
        np.where(marks>=50 , 'B' , 'C'))
print(marks)
print(condi)
condi2 = np.where(marks>=50, 'B', 
        np.where(marks>=75 , 'A' , 'C'))
print(condi2)

[92 61 45 78 33 55]
['A' 'B' 'C' 'A' 'C' 'B']
['B' 'B' 'C' 'B' 'C' 'B']


In [18]:
marks = np.array([92, 61, 45, 78, 33, 55])
idx = np.where(marks > 50)[0]
print("Raw return:" , idx)
idx2 = np.where(marks > 50)
print(idx2)

Raw return: [0 1 3 5]
(array([0, 1, 3, 5]),)


In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a * b   :" , a * b)
print("np.dot  :" , np.dot(a,b))
print("a@b     :" , a @ b)

a * b   : [ 4 10 18]
np.dot  : 32
a@b     : 32


In [ ]:
a = np.array([[1, 2, 3], [7,8,9]])
b = np.array([[4, 5, 6], [10, 11, 12]])
print(a)
print(a.T)
print(a@a.T)
# print(a@b)

[[1 2 3]
 [7 8 9]]
[[1 7]
 [2 8]
 [3 9]]
[[ 14  50]
 [ 50 194]]


In [ ]:
#Assignment 1

s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([['62', '72', '55' , '80'],
                ['49', '53', '66' , '73']])

#SOLUTION

#Q1
table = np.array([s1, s2, s3])
print(table)

#Q2
print(f"no. of students {table.shape[0]} no. of subject {table.shape[1]}")

#Q3
print("Total number of marks enteries" , table.size)

#Q4
# print(table.astype(float))

#Q5
old = old.astype('int32')
print(np.sum(old, axis=1))

print(table.astype(float))
print(np.vstack((table, old)))


[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
no. of students 3 no. of subject 4
Total number of marks enteries 12
[269 241]
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  72  55  80]
 [ 49  53  66  73]]


In [43]:
#Assignment 2

arr = np.zeros((6, 4))
print(arr)
print(np.full)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<function full at 0x10965eda0>
