In [1]:
import numpy as np


In [7]:
arr = np.array([1, 2.5,"hello"])
x = np.array([1, 2.5, 5.6])
print(arr)
print(x)
print(x.dtype)

['1' '2.5' 'hello']
[1.  2.5 5.6]
float64


In [8]:
x = np.array([1, 4, 4.3, 4.9, 4.8], dtype='int32')
print(x)

[1 4 4 4 4]


In [11]:
x = np.array([1, 4, 4.3, 4.9, 4.8])
print(x)
print(x.astype('int32'))
print(x)

[1.  4.  4.3 4.9 4.8]
[1 4 4 4 4]
[1.  4.  4.3 4.9 4.8]


In [19]:
#BASIC OPERATORS
arr1 = np.arange(10)
print(arr1)
print("Add",arr1+5)
print("Multiply", arr1*5)
print("Divide", arr1%5)
print("Exponent", arr1**2)

[0 1 2 3 4 5 6 7 8 9]
Add [ 5  6  7  8  9 10 11 12 13 14]
Multiply [ 0  5 10 15 20 25 30 35 40 45]
Divide [0 1 2 3 4 0 1 2 3 4]
Exponent [ 0  1  4  9 16 25 36 49 64 81]


In [22]:
x = np.arange(10)   #length should be same
y = np.arange(11, 21)
print(x)
print(y)
print(x*y)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[  0  12  26  42  60  80 102 126 152 180]


In [26]:
x = np.arange(6).reshape(2,3)
y = np.arange(3).reshape(1, 3)
print("x is" , x)
print("y is" , y)
print(x + y)

x is [[0 1 2]
 [3 4 5]]
y is [[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [28]:
x = np.arange(6).reshape(2,3)
y = np.arange(6).reshape(3,2)
print("x is" , x)
print("y is" , y)
print(x + y)

x is [[0 1 2]
 [3 4 5]]
y is [[0 1]
 [2 3]
 [4 5]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [33]:
#COMPARISION OPERATOR
x = np.arange(5)
y = np.arange(1,6)
print(x)
print(y)
print(x == y)
print(x > y)
print(x < y)
# print(x != y)



[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [ ]:
arr = np.array([3,4,5,10,25,56,7,8])
print(arr)

In [152]:
# np.random MODULE

# np.random.seed(2)
# np.random.rand(5)#uniform distribution range is fixed
np.random.randn(10) #normal distribution range not fixed


array([ 0.46509623,  1.59823275,  1.51233436, -0.60884842, -0.22794657,
        1.45558119, -0.17645266,  0.91603628, -1.7605467 ,  0.90370431])

In [ ]:
#np.random.randint(low, high, size)
# np.random.seed(10)
np.random.randint(10, 20, size=(5, 3))


array([[19, 14, 10],
       [11, 19, 10],
       [11, 18, 19],
       [10, 18, 16],
       [14, 13, 10]])

In [203]:
lst = [3,4,56,7,9]
# np.random.seed(10)
# np.random.choice(lst,3)
# np.random.choice(lst,3,replace=False)
np.random.choice(10,5, replace=False)

array([0, 7, 9, 1, 4])

In [211]:
arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

[3 1 4 9 2 8 0 5 6 7]


In [219]:
#Q1
np.random.seed(42)
np.random.randint(1, 7, 10)


array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5])

In [223]:
np.random.randint(10,50, size=(3, 4))

array([[44, 23, 26, 45],
       [49, 13, 11, 15],
       [13, 38, 27, 35]])

In [ ]:
arr = ['Aman' , 'Priya' , 'Rahul' , 'Sneha' , 'Vikram']
np.random.choice(arr,3, replace=False)

array(['Vikram', 'Priya', 'Aman'], dtype='<U6')

In [232]:
#BASIC STATISTICS

arr = np.arange(6).reshape(2,3)
print(arr)
print("min", arr.min())
print("row minimum" , arr.min(axis=1))
print("column minimum" , arr.min(axis=0))

print("min", arr.max())
print("row minimum" , arr.max(axis=1))
print("column minimum" , arr.max(axis=0))

[[0 1 2]
 [3 4 5]]
min 0
row minimum [0 3]
column minimum [0 1 2]
min 5
row minimum [2 5]
column minimum [3 4 5]


In [ ]:
arr = np.arange(6).reshape(2,3)
print(arr)
print("sum of the arr" , arr.sum())
print("sum of the row" , arr.sum(axis=1))
print("sum of the col" , arr.sum(axis=0))

[[0 1 2]
 [3 4 5]]
sum of the arr 15
sum of the row [ 3 12]
sum of the col [3 5 7]


In [236]:
arr = np.arange(6).reshape(2,3)
print(arr)
print(np.median(arr))
print(np.median(arr, axis=0)) #col
print(np.median(arr, axis=1)) #row

[[0 1 2]
 [3 4 5]]
2.5
[1.5 2.5 3.5]
[1. 4.]
