In [1]:
import numpy as np

In [2]:
#ADVANCED NUMPY 
#BROADCASTING

arr = np.arange(24).reshape(3,4,2)
arr1 = np.arange(12).reshape(3,4)
print(arr + arr1)

ValueError: operands could not be broadcast together with shapes (3,4,2) (3,4) 

In [ ]:
#RESHAPING - rowa and columns size must match
#reshape(rows, cols)

arr = np.arange(12).reshape(4, -1)
# arr2 = arr.reshape(5,-1)
print(arr)
print(arr.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [11]:
arr = np.arange(10)
print(arr.shape)

arr1 = arr.reshape(1,-1) #row vector
arr2 = arr.reshape(-1, 1) # column vectior

print("Row vector" , arr1)
print("Column vector" , arr2)

(10,)
Row vector [[0 1 2 3 4 5 6 7 8 9]]
Column vector [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [13]:
#np.newaxis - turn 1D into Row / Column vector

arr1 = np.arange(12)
arr1 = arr1[:,np.newaxis]
print(arr1.shape)

(12, 1)


In [22]:
#flatten and ravel

arr = np.arange(12).reshape(4,3)
# print(arr)
arr1 = arr.ravel()
arr1[0] = 99
arr2 = arr.flatten()
arr2[1] = 100
print("Original Array", arr)
print("Ravel array", arr1)
print("Flatten array", arr2)

print(arr1)

Original Array [[99  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Ravel array [99  1  2  3  4  5  6  7  8  9 10 11]
Flatten array [ 99 100   2   3   4   5   6   7   8   9  10  11]
[99  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
#Q1

arr = np.ones((3,4)).reshape(3,1)
print(arr)

arrM = [10, 20, 30]

ValueError: cannot reshape array of size 12 into shape (3,1)

In [34]:
#np.vstack() and np.hstack

arr1 = np.array([[1,3,4], [2,3,5]])
arr2 = np.array([[5,6,7] , [8,9,10], [10,11,14]])
arr4 = np.arange(12).reshape(2,6)
print(arr1)
print(arr2)
arr3 = np.vstack((arr1, arr2))

print("vstack",arr3)
print("hstack",np.hstack((arr1, arr4)))

[[1 3 4]
 [2 3 5]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]]
vstack [[ 1  3  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 14]]
hstack [[ 1  3  4  0  1  2  3  4  5]
 [ 2  3  5  6  7  8  9 10 11]]


In [40]:
#np.concatenate() with axis
#axis -> 0 vstack
#axis -> 1 hstack

print(arr1)
print(arr4)

print(np.concatenate((arr4, arr1) , axis=1))
print(np.concatenate((arr2, arr1) , axis=0))


[[1 3 4]
 [2 3 5]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3  4  5  1  3  4]
 [ 6  7  8  9 10 11  2  3  5]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]
 [ 1  3  4]
 [ 2  3  5]]


In [ ]:
#np.where(condition, true_val, false_val)
#doesnt chnage the original array

arr = np.array([2, -10, 20, -15, -18, 10])
arr1 = np.where(arr<0, 0, arr)
print(arr)
print(arr1)
print(arr)

arr2 = np.array([20,40,55,75,80,35])
arr3 = np.where(arr2<=40, "fail" , "1" )
print(arr3)

['fail' 'fail' '1' '1' '1' 'fail']


In [ ]:
arr2 = np.array([20,40,55,75,80,35])