In [166]:
import numpy as np

# NumPy Practice Session

Quick one-line recaps only — the focus here is practice. For each topic, solve the questions in the empty code cells provided.


## 1. Array Creation Basics

_`np.array(list)` → from list | `np.zeros(shape)` → all 0s | `np.ones(shape)` → all 1s | `np.full(shape, val)` → custom value | `np.arange(start,stop,step)` → like range()_


**Q1.1** Create a 1D array of 6 numbers of your choice.

In [167]:
# Write your code here

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


**Q1.2** Create a 3x3 array of zeros and a 2x2 array filled with the value 7.

In [168]:
# Write your code here

arr1 = np.zeros((3, 3))
arr2 = np.full((2,2) , 7)

print(arr1)
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7]
 [7 7]]


**Q1.3** Create an array of odd numbers from 1 to 21 using `arange`.

In [169]:
# Write your code here

arr3 = np.arange(1, 22, 2)
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19 21]


## 2. Advanced Creation

_`.reshape(r,c)` → change shape | `np.linspace(start,stop,num)` → num evenly spaced values | `np.eye(n)` → n×n identity matrix_


**Q2.1** Create numbers 0 to 11 using `arange` and reshape into a 3x4 matrix.

In [170]:
# Write your code here

arr4 = np.arange(0,12).reshape(3,4)
print(arr4)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q2.2** Generate 7 evenly spaced values between 10 and 50 using `linspace`.

In [171]:
# Write your code here

arr5 = np.linspace(10, 50, 7)
print(arr5)

[10.         16.66666667 23.33333333 30.         36.66666667 43.33333333
 50.        ]


**Q2.3** Create a 5x5 identity matrix.

In [172]:
# Write your code here

arr6 = np.eye(5)
print(arr6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 3. Array Attributes

_`.shape` → dimensions tuple | `.ndim` → no. of dimensions | `.size` → total elements | `.dtype` → data type_


**Q3.1** Create a (4,3) array and print its shape, ndim, size, and dtype.

In [173]:
# Write your code here

arr7 = np.arange(0,12).reshape(3,4)
print(arr7)
print("shape" , arr7.shape)
print("ndim" , arr7.ndim)
print("size" , arr7.size)
print("dtype:" , arr.dtype)

print(arr7)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape (3, 4)
ndim 2
size 12
dtype: int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q3.2** Create a (3,) vector and check if it's compatible for a dot product with a (5,3) matrix.

In [174]:
# Write your code here

vec = np.array([1, 2, 3])
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

result = np.dot(mat, vec)
print(result)

[14 32 50 68 86]


## 4. Indexing & Slicing

_`arr[i]` / `arr[r,c]` → access | `arr[a:b, c:d]` → sub-matrix | `arr[::step]` → step slicing | `arr[::-1]` → reverse_


**Q4.1** Create a 4x4 array with values 1-16. Extract row 2, column 3.

In [175]:
# Write your code here
arr8 = np.arange(0,16).reshape(4,4)
print(arr8)
print(arr8[2,3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
11


**Q4.2** From the same array, extract the sub-matrix of the first two rows and last two columns.

In [176]:
# Write your code here
print(arr8[0:2, -2:])

[[2 3]
 [6 7]]


**Q4.3** Reverse the array row-wise, then column-wise.

In [177]:
# Write your code here
print(arr8)
print(arr8[::-1])
print(arr8[:,::-1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


**Q4.4** Print every 3rd element of a 1-20 array.

In [178]:
# Write your code here

arr9 = np.arange(1,21)
print(arr9[::3])

[ 1  4  7 10 13 16 19]


## 5. Data Types & Coercion

_Mixed types auto-upcast to one common dtype | `.astype(type)` → explicit conversion_


**Q5.1** Create an array mixing ints and floats — check the resulting dtype.

In [179]:
# Write your code here

arr10 = np.array([1, 2, 3.4, 5.7, 7.8, 10])
print(arr10.dtype)
print(arr10.astype("int64"))


float64
[ 1  2  3  5  7 10]


**Q5.2** Convert a float array [1.9, 2.5, 3.1] to integers using astype.

In [180]:
# Write your code here
arr11 = np.array([1.9, 2.5, 3.1])
print(arr11.astype("int64"))



[1 2 3]


## 6. Vectorized Arithmetic & Boolean Masking

_`a + b`, `a * b`, `a ** 2` → element-wise ops | `arr[arr > x]` → boolean filtering_


**Q6.1** Create two same-size arrays and compute their sum, product, and squares.

In [181]:
# Write your code here
yay = np.array([1, 2, 3])
nay = np.array([5, 6, 7])

print(yay + nay)
print(yay * nay)
print(yay ** 2)
print(nay ** 2)

[ 6  8 10]
[ 5 12 21]
[1 4 9]
[25 36 49]


**Q6.2** Create an array of 10 random-looking numbers of your choice, then filter out only values greater than 15 using a boolean mask.

In [182]:
# Write your code here
arr12 = np.array([1, 5, 3, 9, 10,  23, 45, 35, 16, 40, 90, 465, 765])
print(arr12[arr12>15])

[ 23  45  35  16  40  90 465 765]


## 7. Random Module

_`np.random.seed(n)` → reproducibility | `.rand()` → uniform | `.randn()` → normal | `.randint(low,high,size)` → random ints | `.choice(arr,size)` → random sample | `.shuffle(arr)` → shuffle in place_


**Q7.1** Set a seed, generate a 3x3 uniform random array, and confirm reproducibility by rerunning with the same seed.

In [183]:
# Write your code here

np.random.seed(42)
bleh = np.random.rand(3, 3)
print(bleh)

np.random.seed(42)
gleh = np.random.rand(3, 3)
print(gleh)




[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


**Q7.2** Generate 5 values from a normal distribution and 5 random integers between 1-100.

In [184]:
# Write your code here


**Q7.3** Randomly pick 3 values (no repeats) from a list of 8 items, then shuffle a 1-10 array.

In [185]:
# Write your code here


## 8. Reduction & Axis Rules

_`.sum()` / `.mean()` / `np.median()` → aggregations | `axis=0` → column-wise | `axis=1` → row-wise_


**Q8.1** Create a 3x3 matrix. Find the total sum, sum along axis=0, sum along axis=1.

In [186]:
# Write your code here

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix.sum())
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


**Q8.2** Find the mean and median of the same matrix.

In [187]:
# Write your code here

print(matrix.mean())

print(np.median(matrix))

5.0
5.0


## 9. Broadcasting

_Shapes match if equal or one of them is 1 (compared right to left) | smaller array auto-expands to fit_


**Q9.1** Add a (3,3) ones matrix with a 1D array of length 3 — observe the broadcast.

In [188]:
# Write your code here

a1 = np.ones((3,3))
a2 = np.array([1, 2, 3,])
print(a1 + a2)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


**Q9.2** Create a row vector (1,3) and column vector (3,1), add them, and check the resulting shape.

In [189]:
# Write your code here

a3 = np.arange(1,4).reshape(1,3)
a4 = np.arange(1,4).reshape(3,1)

print(a3 + a4)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


## 10. Reshaping & Dimension Expansion

_`reshape(-1, n)` → auto-calculate the other dimension | `arr[np.newaxis, :]` → row vector | `arr[:, np.newaxis]` → column vector_


**Q10.1** Create a 12-element array and reshape it using -1 so it has 4 columns.

In [190]:
# Write your code here

asap = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(-1, 4)
print(asap)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Q10.2** Take a 3-element 1D array and convert it into a row vector and a column vector using np.newaxis.

In [191]:
# Write your code here

assUp = np.array([1, 2, 3])
print(assUp)
print(assUp[np.newaxis, :])
print(assUp[:, np.newaxis])

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


## 11. Flatten vs Ravel

_`.flatten()` → returns a copy (original safe) | `.ravel()` → returns a view (original can change too)_


**Q11.1** Create a 2D array, flatten it with both methods, modify the first element of each result, and check which one affects the original array.

In [192]:
# Write your code here

bummy = np.array([[1, 2, 3], [4, 5, 6]])
b = bummy.flatten()
c = bummy.ravel()
b[0] = 89
c[0] = 67
print(bummy)
print(b)
print(c)

[[67  2  3]
 [ 4  5  6]]
[89  2  3  4  5  6]
[67  2  3  4  5  6]


## 12. Stacking & Concatenation

_`np.vstack()` → stack rows | `np.hstack()` → stack columns | `np.concatenate(axis=)` → general version_


**Q12.1** Create two 2x2 arrays. Combine them using vstack, hstack, and concatenate on both axis=0 and axis=1.

In [193]:
# Write your code here

mj = np.array([[1, 2,], [3, 4]])
aj = np.array([[4, 5,], [6, 7]])

print(mj)
print(aj)

print(np.vstack((mj, aj)))
print(np.hstack((mj, aj)))

print(np.concatenate((mj, aj) , axis=0))
print(np.concatenate((mj, aj) , axis=1))

[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]
[[1 2 4 5]
 [3 4 6 7]]


## 13. np.where — Conditional Logic

_`np.where(cond, a, b)` → element-wise if/else | `np.where(cond)` → returns matching indices_


**Q13.1** Create a 6-element array. Label each value 'High' or 'Low' based on a threshold using np.where.

In [194]:
# Write your code here

bay = np.array([10, 65, 40, 55, 40, 85])
threshyy = 40
print(np.where(bay>=threshyy, "highkeyy" , "lowwkeyy"))

['lowwkeyy' 'highkeyy' 'highkeyy' 'highkeyy' 'highkeyy' 'highkeyy']


**Q13.2** Use np.where (without true/false args) to find the indices of values above that threshold.

In [195]:
# Write your code here

bay = np.array([10, 65, 40, 55, 40, 85])
threshyy = 40
print(np.where(bay>threshyy,))

(array([1, 3, 5]),)


## 14. Matrix Operations & Transpose

_`*` → element-wise multiply | `@` / `np.dot()` → matrix multiplication | `.T` → transpose (rows ↔ cols)_


**Q14.1** Create two 2x2 matrices. Compute their element-wise product and their matrix product (using both @ and np.dot).

In [196]:
# Write your code here
j = np.array([[1, 2,], [3, 4]])
cj = np.array([[4, 5,], [6, 7]])

print(j*cj)
print(j@cj)
print(np.dot(j, cj))
print(j.T)
print(cj.T)

[[ 4 10]
 [18 28]]
[[16 19]
 [36 43]]
[[16 19]
 [36 43]]
[[1 3]
 [2 4]]
[[4 6]
 [5 7]]


**Q14.2** Print the transpose of the first matrix.

In [197]:
# Write your code here
print(j.T)


[[1 3]
 [2 4]]


---
## CRUD Operations on Arrays

_Create, Read, Update, Delete/Insert — arrays are fixed-size, so delete/insert return a new array rather than modifying in place._


## 15. CRUD — Create & Read

_Create = `np.array()`/creation helpers | Read = indexing & slicing_


**Q15.1** Create a 1D array of 8 integers and a 2D array of shape (3,3).

In [198]:
# Write your code here

abrr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
twoD = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

**Q15.2** Read the element at index 3 from the 1D array, and the middle row from the 2D array.

In [199]:
# Write your code here

print(abrr[3])
print(twoD[1])

4
[4 5 6]


## 16. CRUD — Update

_`arr[i] = val` or `arr[slice] = val` → updates values directly (arrays are mutable)_


**Q16.1** Update index 2 of your 1D array to 100.

In [200]:
# Write your code here

baby = np.arange(1,101)
baby[2] = 67
print(baby)

[  1   2  67   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


**Q16.2** Update the entire second row of your 2D array to [0, 0, 0].

In [204]:
# Write your code here

base = np.arange(1,100).reshape(9,11)
base[4] = [0,0,0,0,0,0,0,0,0,0,0]
print(base)

[[ 1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30 31 32 33]
 [34 35 36 37 38 39 40 41 42 43 44]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [56 57 58 59 60 61 62 63 64 65 66]
 [67 68 69 70 71 72 73 74 75 76 77]
 [78 79 80 81 82 83 84 85 86 87 88]
 [89 90 91 92 93 94 95 96 97 98 99]]


## 17. CRUD — Delete & Insert

_`np.delete(arr, idx, axis=)` → remove & return new array | `np.insert(arr, idx, val)` → insert value | `np.append(arr, val)` → add at the end_


**Q17.1** Delete the element at index 0 from your 1D array (store as a new variable).

In [210]:
# Write your code here

dell = np.delete(baby, 2, axis=0)
print(dell)

[  1   2   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100]


**Q17.2** Delete the last column from your 2D array.

In [220]:
# Write your code here

basee = np.arange(1,10).reshape(3,3)
dele = np.delete(basee, -1, axis=1)
print(dele)

[[1 2]
 [4 5]
 [7 8]]


**Q17.3** Use np.append to add 99 to the end of your 1D array, and np.insert to insert 50 at index 1.

In [221]:
# Write your code here
app = np.append(basee, 99)
ins = np.insert(basee, 1, 50)

print(app)
print(ins)

[ 1  2  3  4  5  6  7  8  9 99]
[ 1 50  2  3  4  5  6  7  8  9]


## 18. Combined Practice

_No new functions — just combining what's covered above_


**Q18.1** Create a 5x5 array (1-25), extract its center 3x3 block, then find the row-wise sum of that block.

In [ ]:
# Write your code here

combine = np.arange(1, 26).reshape(5,5)
extract = combine[1:4 , 1:4]
print(combine)
print()

**Q18.2** Create two 1D int arrays, stack them with vstack, add 0.5 to the result and check the dtype coercion.

In [ ]:
# Write your code here


**Q18.3** Create a 4x4 matrix with np.diag() using diagonal values 2,4,6,8, then find its transpose.

In [ ]:
# Write your code here
