In [1]:
import numpy as np

Q1.
A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

In [2]:
# Q1

marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus = np.array([5, 2, 8])

marks = marks + bonus

marks = np.minimum(marks, 100)

print(marks)

capped = np.sum(marks == 100)

print("Number of marks capped:", capped)

[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Number of marks capped: 4


Q2.
Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

In [3]:
# Q2

matrix = np.ones((5, 5), dtype=int)

matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Q3.
Without running the code, predict the shape of np.arange(30).reshape(5, -1).T. Write your prediction as a comment, then verify it. Also explain in a comment why np.arange(30).reshape(4, -1) fails.

In [4]:
# Q3

# Prediction: reshape(5, -1) gives (5, 6), then .T gives (6, 5)

arr = np.arange(30).reshape(5, -1).T

print(arr)
print("Shape:", arr.shape)

# np.arange(30).reshape(4, -1) fails because
# 30 elements cannot be evenly divided into 4 rows.

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]
Shape: (6, 5)


Q4.
Two arrays of size 4 are given. First join them with hstack and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

In [5]:
# Q4

heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

first = np.hstack((heights, weights))

print("First attempt:")
print(first)
print("Shape:", first.shape)

table = np.column_stack((heights, weights))

print("\nProper 2-column table:")
print(table)
print("Shape:", table.shape)

# np.hstack joins two 1-D arrays into one longer 1-D array,
# so its shape is (8,), not (4, 2).

First attempt:
[172 158 181 166  68  52  84  59]
Shape: (8,)

Proper 2-column table:
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
Shape: (4, 2)


Q5.
Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

In [6]:
# Q5

sales = np.array([120, 135, 98,
                  160, 175, 190,
                  88, 92, 105,
                  210, 198, 230])

quarters = sales.reshape(4, 3)

print("Quarterly sales:")
print(quarters)

averages = quarters.mean(axis=1)

print("\nQuarter averages:")
print(averages)

highest_quarter = averages.argmax()

print("\nHighest average quarter index:", highest_quarter)
print("Highest average:", averages[highest_quarter])

Quarterly sales:
[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]

Quarter averages:
[117.66666667 175.          95.         212.66666667]

Highest average quarter index: 3
Highest average: 212.66666666666666


Q6.
Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use np.outer — reshape one of the operands so that broadcasting produces the grid.

a = np.array([2, 3, 4])

In [7]:
# Q6

a = np.array([2, 3, 4])

table = a[:, np.newaxis] * a[np.newaxis, :]

print(table)
print("Shape:", table.shape)

[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]
Shape: (3, 3)


Q7.
Create an array of numbers from 1 to 20 and replace every multiple of 3 with -1.

In [8]:
# Q7

arr = np.arange(1, 21)

arr = np.where(arr % 3 == 0, -1, arr)

print(arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


Q8.
For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization (x - col_min) / (col_max - col_min). Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])

In [9]:
# Q8

X = np.array([[50, 1200, 3],
              [80, 1500, 9],
              [65, 900, 5],
              [95, 2000, 7]])

col_min = X.min(axis=0)
col_max = X.max(axis=0)

normalized = (X - col_min) / (col_max - col_min)

print(normalized)

print("\nColumn minimums:")
print(normalized.min(axis=0))

print("\nColumn maximums:")
print(normalized.max(axis=0))

[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]

Column minimums:
[0. 0. 0.]

Column maximums:
[1. 1. 1.]


Q9.
Award medals to the scores below using nested np.where: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

In [10]:
# Q9

scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(
    scores >= 90,
    "Gold",
    np.where(
        scores >= 75,
        "Silver",
        np.where(
            scores >= 60,
            "Bronze",
            "None"
        )
    )
)

print(medals)

print("\nGold:", np.sum(medals == "Gold"))
print("Silver:", np.sum(medals == "Silver"))
print("Bronze:", np.sum(medals == "Bronze"))
print("None:", np.sum(medals == "None"))

['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']

Gold: 2
Silver: 2
Bronze: 2
None: 2


Q10.
Given the matrix below, use np.where with a single condition to obtain the row and column indices of every element greater than 50, print those elements, and then replace them with 0 in a copy of the matrix while leaving the original untouched.

m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

In [11]:
# Q10

m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols = np.where(m > 50)

print("Row indices:", rows)
print("Column indices:", cols)

print("Elements:", m[rows, cols])

result = m.copy()

result[m > 50] = 0

print("\nOriginal matrix:")
print(m)

print("\nModified copy:")
print(result)

Row indices: [0 1 1 2]
Column indices: [1 0 2 0]
Elements: [80 55 99 70]

Original matrix:
[[10 80 45]
 [55 20 99]
 [70 33 12]]

Modified copy:
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]


Q11.
Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and separately stack them so that each sensor becomes a column. Print both shapes and confirm that one is the transpose of the other.

s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

In [12]:
# Q11

s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

rows = np.vstack((s1, s2, s3))
columns = np.column_stack((s1, s2, s3))

print("Sensors as rows:")
print(rows)
print("Shape:", rows.shape)

print("\nSensors as columns:")
print(columns)
print("Shape:", columns.shape)

print("\nTranspose check:")
print(np.array_equal(rows.T, columns))

Sensors as rows:
[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
Shape: (3, 5)

Sensors as columns:
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
Shape: (5, 3)

Transpose check:
True


Q12.
Create a random 6x6 matrix with seed = 1 and values between 1 and 100, then find the row-wise maximum and the column-wise minimum.

In [13]:
# Q12

np.random.seed(1)

matrix = np.random.randint(1, 101, (6, 6))

print("Matrix:")
print(matrix)

row_max = matrix.max(axis=1)
col_min = matrix.min(axis=0)

print("\nRow-wise maximum:")
print(row_max)

print("\nColumn-wise minimum:")
print(col_min)

Matrix:
[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]

Row-wise maximum:
[76 80 85 69 97 64]

Column-wise minimum:
[ 7  8 17  2 19  6]


Q13.
A and B are both 2x3 matrices. Compute A @ B.T and A.T @ B. Print the shape of each result and explain in a comment why both multiplications are legal while A @ B is not.

A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])

In [14]:
# Q13

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [1, 0, 2]])

result1 = A @ B.T

print("A @ B.T:")
print(result1)
print("Shape:", result1.shape)

result2 = A.T @ B

print("\nA.T @ B:")
print(result2)
print("Shape:", result2.shape)

# Both are legal because:
# A is (2,3), B.T is (3,2)  -> result (2,2)
# A.T is (3,2), B is (2,3)  -> result (3,3)
# A @ B is not legal because (2,3) @ (2,3)
# has mismatched inner dimensions 3 and 2.

A @ B.T:
[[ 50   7]
 [122  16]]
Shape: (2, 2)

A.T @ B:
[[11  8 17]
 [19 16 28]
 [27 24 39]]
Shape: (3, 3)


Q14.
Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column vectors, join them into a single two-column table, attach a third column holding each row's total, then multiply the three-column table by w = [0.5, 0.2, 0.3] to obtain one score per row. Finally use np.where to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of every intermediate array.

hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

In [15]:
# Q14

hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

# Step 1: Convert to column vectors
hours_col = hours.reshape(-1, 1)
attendance_col = attendance.reshape(-1, 1)

print("hours_col shape:", hours_col.shape)
print("attendance_col shape:", attendance_col.shape)

# Step 2: Join into 2-column table
table = np.hstack((hours_col, attendance_col))

print("\n2-column table:")
print(table)
print("Shape:", table.shape)

# Step 3: Add row total as third column
totals = table.sum(axis=1).reshape(-1, 1)

three_col = np.hstack((table, totals))

print("\nThree-column table:")
print(three_col)
print("Shape:", three_col.shape)

# Step 4: Weighted score
w = np.array([0.5, 0.2, 0.3])

scores = three_col @ w

print("\nScores:")
print(scores)
print("Shape:", scores.shape)

# Step 5: Average
average = scores.mean()

print("\nAverage score:", average)

# Step 6: Mark above average as 1, otherwise 0
result = np.where(scores > average, 1, 0)

print("\nFinal result:")
print(result)
print("Shape:", result.shape)

hours_col shape: (6, 1)
attendance_col shape: (6, 1)

2-column table:
[[ 2 55]
 [ 8 92]
 [ 5 70]
 [10 98]
 [ 3 60]
 [ 7 85]]
Shape: (6, 2)

Three-column table:
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
Shape: (6, 3)

Scores:
[29.1 52.4 39.  57.  32.4 48.1]
Shape: (6,)

Average score: 43.0

Final result:
[0 1 0 1 0 1]
Shape: (6,)


Q15.
Apply min-max normalization to scale any array into the 0 to 1 range using (x - min) / (max - min).

In [16]:
# Q15

arr = np.array([10, 20, 30, 40, 50])

minimum = arr.min()
maximum = arr.max()

normalized = (arr - minimum) / (maximum - minimum)

print("Original:")
print(arr)

print("\nNormalized:")
print(normalized)

print("\nMinimum:", normalized.min())
print("Maximum:", normalized.max())

Original:
[10 20 30 40 50]

Normalized:
[0.   0.25 0.5  0.75 1.  ]

Minimum: 0.0
Maximum: 1.0


Q16.
Take the array below and create two 1D versions of it — one with flatten() and one with ravel(). Change the first element of each, then print the original matrix. Explain the difference you observe in a comment.

m = np.array([[4, 8, 15],
              [16, 23, 42]])

In [17]:
# Q16

m = np.array([[4, 8, 15],
              [16, 23, 42]])

flat = m.flatten()
rav = m.ravel()

flat[0] = 999
rav[0] = 999

print("Original matrix:")
print(m)

print("\nflatten():")
print(flat)

print("\nravel():")
print(rav)

# flatten() creates a copy, so changing flat does not affect m.
# ravel() usually returns a view, so changing rav changes m.

Original matrix:
[[999   8  15]
 [ 16  23  42]]

flatten():
[999   8  15  16  23  42]

ravel():
[999   8  15  16  23  42]


Q17.
28 daily temperature readings are given. Reshape them into 4 weeks of 7 days, then: find each week's average, identify the hottest week, and count how many individual days crossed 35 degrees.

np.random.seed(7)
temps = np.random.randint(15, 41, 28)

In [18]:
# Q17

np.random.seed(7)

temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)

print("4 weeks:")
print(weeks)

weekly_avg = weeks.mean(axis=1)

print("\nWeekly averages:")
print(weekly_avg)

hottest_week = weekly_avg.argmax()

print("\nHottest week index:", hottest_week)
print("Hottest week average:", weekly_avg[hottest_week])

days_above_35 = np.sum(temps > 35)

print("\nDays above 35°C:", days_above_35)

4 weeks:
[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]]

Weekly averages:
[30.85714286 31.57142857 23.28571429 26.85714286]

Hottest week index: 1
Hottest week average: 31.571428571428573

Days above 35°C: 7


Q18.
Create two random 3x3 matrices A and B, compute A @ B and B @ A, and check whether the two results are equal. State your conclusion about matrix multiplication in a comment.

In [21]:
# Q18

np.random.seed(10)

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

result_AB = A @ B
result_BA = B @ A

print("A:")
print(A)

print("\nB:")
print(B)

print("\nA @ B:")
print(result_AB)

print("\nB @ A:")
print(result_BA)

print("\nAre they equal?")
print(np.array_equal(result_AB, result_BA))

# Matrix multiplication is generally NOT commutative:
# A @ B != B @ A

A:
[[5 1 2]
 [1 2 9]
 [1 9 7]]

B:
[[5 4 1]
 [5 7 9]
 [2 9 5]]

A @ B:
[[ 34  45  24]
 [ 33  99  64]
 [ 64 130 117]]

B @ A:
[[ 30  22  53]
 [ 41 100 136]
 [ 24  65 120]]

Are they equal?
False


Q19.
Given the marks matrix below (5 students x 4 subjects), first replace every mark below 35 with 35, then compute each student's total, and finally print the index of the topper along with their total.

marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

In [22]:
# Q19

marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

marks = np.maximum(marks, 35)

print("Updated marks:")
print(marks)

totals = marks.sum(axis=1)

print("\nStudent totals:")
print(totals)

topper = totals.argmax()

print("\nTopper index:", topper)
print("Topper total:", totals[topper])

Updated marks:
[[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]

Student totals:
[227 221 231 342 165]

Topper index: 3
Topper total: 342


Q20.
Start from arr = np.arange(1, 11). Create one variable using a plain slice arr[2:6] and another using arr[2:6].copy(). Change the first element of each to 999, then print the original array and explain in a comment which change survived and why.

In [23]:
# Q20

arr = np.arange(1, 11)

view = arr[2:6]
copy = arr[2:6].copy()

view[0] = 999
copy[0] = 999

print("Original array:")
print(arr)

print("\nSlice view:")
print(view)

print("\nCopy:")
print(copy)

# arr[2:6] creates a view, so changing view changes arr.
# arr[2:6].copy() creates an independent copy,
# so changing copy does not affect arr.

Original array:
[  1   2 999   4   5   6   7   8   9  10]

Slice view:
[999   4   5   6]

Copy:
[999   4   5   6]


Q21.
Explore np.diag in the NumPy documentation and use it to extract the diagonal of a 4x4 matrix. Then use the same function in its second role — to build a diagonal matrix from a 1D array.

In [24]:
# Q21

m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Extract diagonal
diagonal = np.diag(m)

print("Diagonal:")
print(diagonal)

# Create diagonal matrix from 1-D array
arr = np.array([10, 20, 30, 40])

diagonal_matrix = np.diag(arr)

print("\nDiagonal matrix:")
print(diagonal_matrix)

Diagonal:
[ 1  6 11 16]

Diagonal matrix:
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


The 7 concepts I would especially memorize

In [26]:
# # Broadcasting
# A + b

# # Reshape
# arr.reshape(rows, cols)

# # Axis
# arr.mean(axis=0)   # column-wise
# arr.mean(axis=1)   # row-wise

# # Conditional replacement
# np.where(condition, value_if_true, value_if_false)

# # Matrix multiplication
# A @ B

# # View vs copy
# view = arr[2:6]
# copy = arr[2:6].copy()

# # Diagonal
# np.diag(matrix)
# np.diag(array)