In [2]:
import numpy as np

Q1. Building the class register
Three students' marks arrived as three separate lists, and one old record arrived as text.

Tasks

Build one table from s1, s2 and s3.
From that table, print the number of students and the number of subjects as two separate numbers.
Print the total count of marks entries stored in the table.
Store the same table as decimals instead of whole numbers.
Convert old into a form where arithmetic works, then print the total marks of both students.
Attach old below the main table so that all five students sit in one table.
Expected output — task 5

[268 246]
Expected output — task 6

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]

In [3]:
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

In [4]:
# Q1

# 1. Build one table
table = np.array([s1, s2, s3])
print(table)

# 2. Number of students and subjects
print("no of students", table.shape[0],
      "no of subject", table.shape[1])

# 3. Total number of marks entries
print("Total no of marks entries", table.size)

# 4. Store table as decimals
decimal_table = table.astype(float)
print(decimal_table)

# 5. Convert old to integers and find total of both students
old_int = old.astype(int)
print(np.sum(old_int, axis=1))

# 6. Attach old below main table
full_table = np.vstack((table, old_int))
print(full_table)

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
no of students 3 no of subject 4
Total no of marks entries 12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[268 246]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


Q2. Templates and sequences
Tasks

Create a blank mark sheet for 6 students and 4 subjects, every entry starting at 0.
Create a table of the same size where every student is temporarily given 35.
A batch has roll numbers running from 101 to 130. Generate only the alternate roll numbers, and print how many were generated.
Split a 3-hour practical into 7 equally spaced time markers, including both the start and the end.
Create a 5 × 5 table that has 10 on the diagonal and 0 everywhere else.
Create a 4 × 4 table that has 100 on the diagonal and 35 everywhere else.
Expected output — task 3

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
Expected output — task 4

[0.  0.5 1.  1.5 2.  2.5 3. ]
Expected output — task 6

[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]

In [5]:
# Q2

# 1. 6 students × 4 subjects, all zero
marks = np.zeros((6, 4), dtype=int)
print(marks)

# 2. Same size, every value = 35
temp_marks = np.full((6, 4), 35)
print(temp_marks)

# 3. Alternate roll numbers from 101 to 130
roll_numbers = np.arange(101, 131, 2)
print(roll_numbers)
print(len(roll_numbers))

# 4. 3-hour practical, 7 equally spaced points
time = np.linspace(0, 3, 7)
print(time)

# 5. 5 × 5 diagonal = 10
table = np.eye(5, dtype=int) * 10
print(table)

# 6. 4 × 4 diagonal = 100, everything else = 35
table2 = np.full((4, 4), 35, dtype=int)
table2[np.eye(4, dtype=bool)] = 100
print(table2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]


Q3. The attendance row
Tasks

Print the first and the last student's attendance without writing the class strength anywhere in your code.
Print the attendance of every alternate student, starting from the second one.
Print the last four values.
Reverse the row, then print every third value of the reversed row.
Change the attendance of the two middle students to 30 each.
Compare the first half of the row with the second half position by position, and print the difference.
Print the top three values of the row after reversing it.
Expected output — task 4

[23  9 12 22]
Expected output — task 6

[-2  9  4 -5 -3]

In [6]:
present = np.array([22, 18, 25, 12, 20, 24, 9, 21, 17, 23])

In [7]:
# Q3
# 1. First and last student
print(present[0])
print(present[-1])

# 2. Every alternate student, starting from second
print(present[1::2])

# 3. Last four values
print(present[-4:])

# 4. Reverse and take every third value
print(present[::-1][::3])

# 5. Change two middle students to 30
temp = present.copy()
temp[len(temp)//2 - 1 : len(temp)//2 + 1] = 30
print(temp)

# 6. First half - second half
mid = len(present) // 2
print(present[:mid] - present[mid:])

# 7. First three values after reversing
print(present[::-1][:3])

22
23
[18 12 24 21 23]
[ 9 21 17 23]
[23  9 12 22]
[22 18 25 12 30 30  9 21 17 23]
[-2  9  4 -5 -3]
[23 17 21]


Q4. Reading the mark sheet
The columns are Math, Physics, Chemistry and English.

Tasks

Print the Physics and Chemistry marks of the middle three students only.
Print the last subject's marks for the whole class.
Produce a table containing only the first and the last subject of every student.
Print the mark sheet with the students in reverse order.
Increase only the Chemistry marks of the whole class by 5, leaving the rest unchanged.
Print the mark that sits in the last row and the second-last column.
Produce a table of the last two students and their first two subjects.
Expected output — task 1

[[30 98]
 [66 74]
 [92 55]]
Expected output — task 3

[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]

In [8]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])

In [9]:
# Q4

# 1. Physics and Chemistry of middle three students
print(marks[1:4, 1:3])

# 2. Last subject of whole class
print(marks[:, -1])

# 3. First and last subject
print(marks[:, [0, -1]])

# 4. Students in reverse order
print(marks[::-1])

# 5. Increase Chemistry by 5 without changing original
new_marks = marks.copy()
new_marks[:, 2] += 5
print(new_marks)

# 6. Last row, second-last column
print(marks[-1, -2])

# 7. Last two students, first two subjects
print(marks[-2:, :2])

[[30 98]
 [66 74]
 [92 55]]
[ 91  55 100  40  70]
[[ 72  91]
 [ 45  55]
 [ 88 100]
 [ 95  40]
 [ 30  70]]
[[ 30  48  62  70]
 [ 95  92  55  40]
 [ 88  66  74 100]
 [ 45  30  98  55]
 [ 72  85  60  91]]
[[ 72  85  65  91]
 [ 45  30 103  55]
 [ 88  66  79 100]
 [ 95  92  60  40]
 [ 30  48  67  70]]
62
[[95 92]
 [30 48]]


Q5. Scholarship shortlisting
Tasks

Print the totals of students who scored above 250.
Print the totals of students scoring above 180 but below 250.
Print the totals of students who scored either below 150 or above 380.
Print how many students fall in the band of task 2.
Print the average of only those students who scored above 200.
Print the index position of every student below 150.
Print the highest total among the students who did not make the merit band of task 1.
Expected output — task 2

[245 199]
2
Expected output — task 6

[4 9]

In [10]:
totals = np.array([245, 310, 178, 392, 140,
                   265, 199, 155, 288, 132])

In [11]:
# Q5

# 1. Students scoring above 250
print(totals[totals > 250])

# 2. Above 180 but below 250
band = totals[(totals > 180) & (totals < 250)]
print(band)
print(len(band))

# 3. Below 150 OR above 380
print(totals[(totals < 150) | (totals > 380)])

# 4. Number of students in task 2
print(np.sum((totals > 180) & (totals < 250)))

# 5. Average of students above 200
print(np.mean(totals[totals > 200]))

# 6. Index of every student below 150
print(np.where(totals < 150)[0])

# 7. Highest total outside merit band (>250)
print(np.max(totals[totals <= 250]))

[310 392 265 288]
[245 199]
2
[392 140 132]
2
300.0
[4 9]
245


Q6. After revaluation
Tasks

Increase every student's marks by 15% and round to 2 decimals.
After the increase, no student may show more than 100. Produce the corrected list.
Print how many students gained less than 10 marks from this increase.
The pass mark is 40. Print how many students were failing before the increase and how many after.
Print each student's marks as a percentage of the topper's marks, rounded to 1 decimal.
Print the total number of marks the school gave away in this revaluation.
Expected output — task 2

[ 46.    63.25  71.3  100.   100.    37.95  81.65  66.7 ]
Expected output — task 5

[ 42.1  57.9  65.3  92.6 100.   34.7  74.7  61.1]

In [12]:
# Q6

# 1. Increase by 15%
increased = np.round(marks * 1.15, 2)
print(increased)

# 2. Cap maximum at 100
corrected = np.minimum(increased, 100)
print(corrected)

# 3. Count students who gained less than 10 marks
gain = corrected - marks
print(np.sum(gain < 10))

# 4. Number failing before and after
before_fail = np.sum(marks < 40)
after_fail = np.sum(corrected < 40)

print(before_fail)
print(after_fail)

# 5. Percentage of topper
percentage = np.round((marks / marks.max()) * 100, 1)
print(percentage)

# 6. Total marks given in revaluation
print(np.sum(corrected - marks))

[[ 82.8   97.75  69.   104.65]
 [ 51.75  34.5  112.7   63.25]
 [101.2   75.9   85.1  115.  ]
 [109.25 105.8   63.25  46.  ]
 [ 34.5   55.2   71.3   80.5 ]]
[[ 82.8   97.75  69.   100.  ]
 [ 51.75  34.5  100.    63.25]
 [100.    75.9   85.1  100.  ]
 [100.   100.    63.25  46.  ]
 [ 34.5   55.2   71.3   80.5 ]]
15
2
2
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]
 [ 95.  92.  55.  40.]
 [ 30.  48.  62.  70.]]
154.8


Q7. The result summary
Tasks

Print the class average and the middle value of the class.
Print the gap between the highest and the lowest marks.
Print the index positions of the topper and of the weakest student.
Print the second highest marks in the class.
Print how many students scored above the class average.
Print how many students lie within one standard deviation of the class average.
Print the class average after removing the topper.
Expected output — task 4

91
Expected output — task 6

5
Expected output — task 7

62.67

In [13]:
marks = np.array([72, 45, 88, 95, 30, 67, 91, 54, 78, 39])

In [14]:
# Q7

# 1. Class average and median
print(np.mean(marks))
print(np.median(marks))

# 2. Gap between highest and lowest
print(np.max(marks) - np.min(marks))

# 3. Index of topper and weakest student
print(np.argmax(marks))
print(np.argmin(marks))

# 4. Second highest marks
print(np.sort(marks)[-2])

# 5. Number above class average
average = np.mean(marks)
print(np.sum(marks > average))

# 6. Number within one standard deviation
std = np.std(marks)
print(np.sum(np.abs(marks - average) <= std))

# 7. Average after removing topper
topper_index = np.argmax(marks)
print(np.mean(np.delete(marks, topper_index)))

65.9
69.5
65
3
4
91
6
5
62.666666666666664


Q8. Subject-wise and student-wise reports
Tasks

Print the average of each subject and the total of each student.
Print the index of the toughest subject for the class.
Print the index of the student who topped overall.
For every subject, print the marks of the student who topped that subject.
Print how many students scored above 60 in each subject.
Print the index of the subject in which the class marks are the most spread out.
Print the total marks of the student who scored the lowest in Chemistry.
Expected output — task 4

[ 95  92  98 100]
Expected output — task 5

[3 3 3 3]
Expected output — task 6

0

In [15]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40],
                  [30, 48, 62, 70]])

In [16]:
# Q8

# 1. Average of each subject and total of each student
subject_average = np.mean(marks, axis=0)
student_total = np.sum(marks, axis=1)

print(subject_average)
print(student_total)

# 2. Index of toughest subject
print(np.argmin(subject_average))

# 3. Index of student who topped overall
print(np.argmax(student_total))

# 4. Highest mark in every subject
print(np.max(marks, axis=0))

# 5. Number of students above 60 in each subject
print(np.sum(marks > 60, axis=0))

# 6. Subject with greatest spread
print(np.argmax(np.std(marks, axis=0)))

# 7. Total of student with lowest Chemistry mark
chemistry_index = np.argmin(marks[:, 2])
print(np.sum(marks[chemistry_index]))

[66.  64.2 69.8 71.2]
[308 228 328 282 210]
1
2
[ 95  92  98 100]
[3 3 3 3]
0
282


Q9. The annual function draw
Tasks

Make the whole draw repeatable, then pick 3 winners from participants.
Generate the attendance percentages of these 10 participants as whole numbers between 60 and 100.
Generate a 4 × 3 table of random decimals between 0 and 1, then turn it into whole-number marks out of 100.
Shuffle the participant list and print the first four as the front-row seating.
Simulate 20 dice rolls and print how many times a 6 appeared.
From the attendance of task 2, print the roll numbers of the participants who crossed 80.
Note: the outputs below appear only if the seed 42 is set before each task. A different seed or a different call order will give different numbers, and that is not wrong.

Expected output — task 1

[107 104 108]
Expected output — task 2

[98 88 74 67 80 98 78 82 70 70]
Expected output — task 5

3

In [17]:
participants = np.array([101, 102, 103, 104, 105,
                         106, 107, 108, 109, 110])

In [18]:
# Q9

# 1. Repeatable draw and pick 3 winners
np.random.seed(42)
winners = np.random.choice(participants, 3)
print(winners)

# 2. Attendance percentages between 60 and 100
np.random.seed(42)
attendance = np.random.randint(60, 101, 10)
print(attendance)

# 3. 4 × 3 random decimals -> marks out of 100
np.random.seed(42)
random_marks = np.random.rand(4, 3)
random_marks = (random_marks * 100).astype(int)
print(random_marks)

# 4. Shuffle participants and select first four
np.random.seed(42)
seating = participants.copy()
np.random.shuffle(seating)
print(seating[:4])

# 5. 20 dice rolls
np.random.seed(42)
dice = np.random.randint(1, 7, 20)
print(np.sum(dice == 6))

# 6. Roll numbers whose attendance crossed 80
print(participants[attendance > 80])

[107 104 108]
[98 88 74 67 80 98 78 82 70 70]
[[37 95 73]
 [59 15 15]
 [ 5 86 60]
 [70  2 96]]
[109 102 106 101]
3
[101 102 106 108]


Q10. Grace marks and weightage
Tasks

Apply the subject-wise grace marks to the whole class, keeping every value at or below 100.
Multiply each subject by its own weightage and print the table rounded to 1 decimal.
Produce a table showing how far each mark sits from that subject's own class average.
Give 5 bonus marks to the first student, 0 to the second, 2 to the third and 0 to the fourth — in a single operation.
From the table of task 3, print how many entries lie below the subject average.
Produce a table where every subject is brought to one scale by subtracting its average and dividing by its spread. Round to 2 decimals.
Expected output — task 3

[[ -3.    16.75 -11.75  19.5 ]
 [-30.   -38.25  26.25 -16.5 ]
 [ 13.    -2.25   2.25  28.5 ]
 [ 20.    23.75 -16.75 -31.5 ]]
Expected output — task 4

[[ 77  90  65  96]
 [ 45  30  98  55]
 [ 90  68  76 102]
 [ 95  92  55  40]]
Expected output — task 6

[[-0.16  0.7  -0.7   0.79]
 [-1.56 -1.59  1.57 -0.67]
 [ 0.68 -0.09  0.13  1.15]
 [ 1.04  0.99 -1.   -1.27]]

In [19]:
marks = np.array([[72, 85, 60, 91],
                  [45, 30, 98, 55],
                  [88, 66, 74, 100],
                  [95, 92, 55, 40]])

grace = np.array([5, 0, 8, 3])
weightage = np.array([1.2, 1.0, 1.1, 1.0])

In [20]:
# Q10

# 1. Apply subject-wise grace, maximum 100
grace_marks = np.minimum(marks + grace, 100)
print(grace_marks)

# 2. Multiply each subject by its weightage
weighted = np.round(marks * weightage, 1)
print(weighted)

# 3. Difference from subject-wise class average
subject_mean = np.mean(marks, axis=0)
difference = marks - subject_mean
print(difference)

# 4. Give row-wise bonus
bonus = np.array([5, 0, 2, 0]).reshape(-1, 1)
bonus_result = marks + bonus
print(bonus_result)

# 5. Count entries below subject average
print(np.sum(difference < 0))

# 6. Standardize every subject
subject_std = np.std(marks, axis=0)
standardized = np.round(
    (marks - subject_mean) / subject_std,
    2
)

print(standardized)

[[ 77  85  68  94]
 [ 50  30 100  58]
 [ 93  66  82 100]
 [100  92  63  43]]
[[ 86.4  85.   66.   91. ]
 [ 54.   30.  107.8  55. ]
 [105.6  66.   81.4 100. ]
 [114.   92.   60.5  40. ]]
[[ -3.    16.75 -11.75  19.5 ]
 [-30.   -38.25  26.25 -16.5 ]
 [ 13.    -2.25   2.25  28.5 ]
 [ 20.    23.75 -16.75 -31.5 ]]
[[ 77  90  65  96]
 [ 45  30  98  55]
 [ 90  68  76 102]
 [ 95  92  55  40]]
8
[[-0.16  0.7  -0.7   0.79]
 [-1.56 -1.59  1.57 -0.67]
 [ 0.68 -0.09  0.13  1.15]
 [ 1.04  0.99 -1.   -1.27]]


Q11. Distances and arrangements
Tasks

Build a 5 × 5 table of walking distances between every pair of hostel blocks, with all values positive.
For each block, print the distance to the block farthest from it.
Print the index of the block nearest to block 0, leaving out block 0 itself.
Print the two blocks that are closest to each other anywhere on the road.
Arrange roll numbers 1 to 24 into rows of 6 without typing the number of rows.
Turn sanskrit into a form that can be attached as a column to a mark sheet, using two different methods.
Turn sanskrit into a single-row table of shape (1, 5).
Expected output — task 1

[[  0 300 700 100 500]
 [300   0 400 400 200]
 [700 400   0 800 200]
 [100 400 800   0 600]
 [500 200 200 600   0]]
Expected output — task 2

[700 400 800 800 600]
Expected output — task 7

[[65 70 88 92 54]]

In [3]:
metres = np.array([200, 500, 900, 100, 700])
sanskrit = np.array([65, 70, 88, 92, 54])

In [6]:
# Q11

# 1. 5 x 5 distance table
distances = np.abs(metres[:, np.newaxis] - metres)
print(distances)

# 2. Farthest distance for each block
print(np.max(distances, axis=1))

# 3. Nearest block to block 0, excluding block 0
row0 = distances[0].astype(float)
row0[0] = np.inf

print(np.argmin(row0))

# 4. Two blocks closest to each other
temp = np.where(
    np.eye(len(metres), dtype=bool),
    np.inf,
    distances
)

i, j = np.unravel_index(np.argmin(temp), temp.shape)
print(np.array([i, j]))

# 5. Roll numbers 1 to 24 in rows of 6
roll_numbers = np.arange(1, 25).reshape(-1, 6)
print(roll_numbers)

# 6. Sanskrit as a column
print(sanskrit.reshape(-1, 1))
print(sanskrit[:, np.newaxis])

# 7. Sanskrit as (1, 5)
print(sanskrit.reshape(1, 5))

[[  0 300 700 100 500]
 [300   0 400 400 200]
 [700 400   0 800 200]
 [100 400 800   0 600]
 [500 200 200 600   0]]
[700 400 800 800 600]
3
[0 3]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[[65]
 [70]
 [88]
 [92]
 [54]]
[[65]
 [70]
 [88]
 [92]
 [54]]
[[65 70 88 92 54]]


Q12. The master mark sheet
Tasks

Produce a flat one-line version of the master that can be edited without affecting the master. Change its first value to 999 and print the master.
Produce a flat version that shares memory with the master. Change its last value to 111 and print the master.
Set the entire middle row to 0 while leaving the master unchanged.
Double the first two columns without changing the master.
Double the first two columns, this time changing the master itself.
Produce a copy of the master in which every value above 50 is reduced by 10, leaving the master untouched.
Expected output — task 1 (master unchanged)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Expected output — task 2 (master changed)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 111]]
Expected output — task 5

[[ 20  40  30]
 [ 80 100  60]
 [140 160  90]]

In [23]:
master = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

In [24]:
# Q12

# 1. flatten() creates a copy
flat = master.flatten()
flat[0] = 999

print(master)


# 2. ravel() creates a view when possible
flat_view = master.ravel()
flat_view[-1] = 111

print(master)


# 3. Middle row = 0 without changing master
temp = master.copy()
temp[1, :] = 0

print(temp)


# 4. Double first two columns without changing master
temp = master.copy()
temp[:, :2] *= 2

print(temp)


# 5. Double first two columns and change master
master[:, :2] *= 2

print(master)


# 6. Copy master and subtract 10 from values > 50
temp = master.copy()
temp[temp > 50] -= 10

print(temp)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80 111]]
[[ 10  20  30]
 [  0   0   0]
 [ 70  80 111]]
[[ 20  40  30]
 [ 80 100  60]
 [140 160 111]]
[[ 20  40  30]
 [ 80 100  60]
 [140 160 111]]
[[ 20  40  30]
 [ 70  90  50]
 [130 150 101]]


Q13. Merging section records
Tasks

Combine Section A and Section B into one mark sheet and print its shape.
Attach a totals column to that combined mark sheet.
Build a two-column table from roll_C and marks_C, roll numbers first.
Add a new student — roll 205, marks 73 — as a fresh row to the table of task 3.
Attach a serial-number column, starting from 1, to the left of the combined mark sheet of task 1.
From the combined sheet, produce a new sheet holding only the students whose total crosses 200.
Attach a grade column to the combined sheet: 225 and above → A, 150 to 224 → B, below 150 → C.
Expected output — task 2

[[ 72  85  60 217]
 [ 45  30  98 173]
 [ 88  66  74 228]
 [ 95  92  55 242]
 [ 30  48  62 140]]
Expected output — task 5

[[ 1 72 85 60]
 [ 2 45 30 98]
 [ 3 88 66 74]
 [ 4 95 92 55]
 [ 5 30 48 62]]
Expected output — task 7

[['72' '85' '60' 'B']
 ['45' '30' '98' 'B']
 ['88' '66' '74' 'A']
 ['95' '92' '55' 'A']
 ['30' '48' '62' 'C']]

In [25]:
sec_A = np.array([[72, 85, 60],
                  [45, 30, 98],
                  [88, 66, 74]])

sec_B = np.array([[95, 92, 55],
                  [30, 48, 62]])

roll_C = np.array([201, 202, 203, 204])
marks_C = np.array([67, 82, 45, 91])

In [26]:
# Q13

# 1. Combine Section A and B
combined = np.vstack((sec_A, sec_B))

print(combined.shape)
print(combined)


# 2. Add totals column
totals = np.sum(combined, axis=1)

combined_total = np.column_stack((combined, totals))

print(combined_total)


# 3. Roll numbers + marks
table_C = np.column_stack((roll_C, marks_C))

print(table_C)


# 4. Add new student
new_student = np.array([[205, 73]])

table_C = np.vstack((table_C, new_student))

print(table_C)


# 5. Add serial number column
serial = np.arange(1, combined.shape[0] + 1).reshape(-1, 1)

serial_table = np.hstack((serial, combined))

print(serial_table)


# 6. Students whose total > 200
above_200 = combined_total[combined_total[:, 3] > 200]

print(above_200)


# 7. Add grade column
grades = np.where(
    combined_total[:, 3] >= 225,
    "A",
    np.where(
        combined_total[:, 3] >= 150,
        "B",
        "C"
    )
)

graded = np.column_stack(
    (combined.astype(str), grades)
)

print(graded)

(5, 3)
[[72 85 60]
 [45 30 98]
 [88 66 74]
 [95 92 55]
 [30 48 62]]
[[ 72  85  60 217]
 [ 45  30  98 173]
 [ 88  66  74 228]
 [ 95  92  55 242]
 [ 30  48  62 140]]
[[201  67]
 [202  82]
 [203  45]
 [204  91]]
[[201  67]
 [202  82]
 [203  45]
 [204  91]
 [205  73]]
[[ 1 72 85 60]
 [ 2 45 30 98]
 [ 3 88 66 74]
 [ 4 95 92 55]
 [ 5 30 48 62]]
[[ 72  85  60 217]
 [ 88  66  74 228]
 [ 95  92  55 242]]
[['72' '85' '60' 'B']
 ['45' '30' '98' 'B']
 ['88' '66' '74' 'A']
 ['95' '92' '55' 'A']
 ['30' '48' '62' 'C']]


Q14. Cleaning and grading
Tasks

Repair the attendance row: every value above 100 becomes 100, and every -1 becomes the average of the genuine entries.
Label each repaired value: 85 and above → Regular, 60 to 84 → Average, below 60 → Short.
Print the index positions of the Short students along with their attendance values.
In the marks table, find the row and column position of every mark below 50.
Print the actual marks sitting at those positions.
Replace every mark below 35 with 35, and print how many entries were changed.
Print the index of the student who has the highest number of marks below 60.
Expected output — task 1

[ 88.    74.75 100.    76.    45.    74.75  92.   100.    67.    30.  ]
Expected output — task 4

rows: [1 3 3]
cols: [2 0 2]
Expected output — task 5

[32 40 45]
Expected output — task 7

3

In [27]:
marks = np.array([[70, 65, 80],
                  [55, 90, 32],
                  [88, 76, 91],
                  [40, 52, 45],
                  [60, 58, 66]])

attendance = np.array([88, -1, 105, 76, 45, -1, 92, 120, 67, 30])

In [28]:
# Q14

# 1. Repair attendance

attendance_clean = attendance.copy()

# Values above 100 become 100
attendance_clean = np.minimum(attendance_clean, 100)

# Average of genuine entries
average = np.mean(attendance_clean[attendance_clean != -1])

# Replace -1 with average
attendance_clean = np.where(
    attendance_clean == -1,
    average,
    attendance_clean
)

print(attendance_clean)


# 2. Label attendance

labels = np.where(
    attendance_clean >= 85,
    "Regular",
    np.where(
        attendance_clean >= 60,
        "Average",
        "Short"
    )
)

print(labels)


# 3. Index and attendance of Short students

short_positions = np.where(attendance_clean < 60)[0]

print(short_positions)
print(attendance_clean[short_positions])


# 4. Row and column positions of marks below 50

rows, cols = np.where(marks < 50)

print("rows:", rows)
print("cols:", cols)


# 5. Actual marks at those positions

print(marks[rows, cols])


# 6. Replace every mark below 35 with 35
count_changed = np.sum(marks < 35)

marks[marks < 35] = 35

print(count_changed)
print(marks)


# 7. Student with highest number of marks below 60

below_60 = np.sum(marks < 60, axis=1)

print(np.argmax(below_60))

[ 88.    74.75 100.    76.    45.    74.75  92.   100.    67.    30.  ]
['Regular' 'Average' 'Regular' 'Average' 'Short' 'Average' 'Regular'
 'Regular' 'Average' 'Short']
[4 9]
[45. 30.]
rows: [1 3 3]
cols: [2 0 2]
[32 40 45]
1
[[70 65 80]
 [55 90 35]
 [88 76 91]
 [40 52 45]
 [60 58 66]]
3


Q15. The final weighted result
Tasks

Compute the weighted final score of every student using w.
Print the index of the student with the highest weighted score.
Using a multiplication rather than sum, produce the subject-wise total marks of the whole class.
The board has proposed two weightage schemes, held in W. Compute both final scores of all four students in one multiplication.
From that result, print how many students score higher under the second scheme.
Print the difference between the two schemes for every student, rounded to 2 decimals.
Attach the better of the two scores as a fourth column to M.
Expected output — task 3

[273. 289. 309.]
Expected output — task 4

[[72.5 72. ]
 [72.3 67.1]
 [85.6 86.5]
 [61.8 61.4]]
Expected output — task 6

[-0.5 -5.2  0.9 -0.4]

In [29]:
M = np.array([[70, 65, 80],
              [55, 90, 72],
              [88, 76, 91],
              [60, 58, 66]])

w = np.array([0.3, 0.3, 0.4])

W = np.array([[0.3, 0.5],
              [0.3, 0.2],
              [0.4, 0.3]])

In [30]:
# Q15

# 1. Weighted final score
final_scores = M @ w

print(final_scores)


# 2. Index of student with highest weighted score
print(np.argmax(final_scores))


# 3. Subject-wise total using multiplication
ones = np.ones(M.shape[0])

subject_totals = ones @ M

print(subject_totals)


# 4. Both weighting schemes in one multiplication
both_scores = M @ W

print(both_scores)


# 5. Number of students scoring higher under second scheme
count = np.sum(both_scores[:, 1] > both_scores[:, 0])

print(count)


# 6. Difference between second and first scheme
difference = np.round(
    both_scores[:, 1] - both_scores[:, 0],
    2
)

print(difference)


# 7. Attach better score as fourth column
better_score = np.max(both_scores, axis=1).reshape(-1, 1)

result = np.hstack((M, better_score))

print(result)

[72.5 72.3 85.6 61.8]
2
[273. 289. 309.]
[[72.5 72. ]
 [72.3 67.1]
 [85.6 86.5]
 [61.8 61.4]]
1
[-0.5 -5.2  0.9 -0.4]
[[70.  65.  80.  72.5]
 [55.  90.  72.  72.3]
 [88.  76.  91.  86.5]
 [60.  58.  66.  61.8]]
